// Package alerts provides canonical root-cause keys and occurrence aggregation
// for automated recovery alerts (e.g., POLECAT_DIED, ZOMBIE_DETECTED).
package alerts

import (
	"fmt"
	"regexp"
	"strings"
)

// AlertClass identifies the category of an automated alert.
type AlertClass string

const (
	// ClassPolecatDied is emitted when polecats die with active work.
	ClassPolecatDied AlertClass = "polecat-died"

	// ClassZombieDetected is emitted when patrol finds zombies with active work.
	ClassZombieDetected AlertClass = "zombie-detected"
)

// canonicalSubjectPrefix maps a subject prefix to its alert class.
// Subjects use the form "CLASS: ..." as generated by patrol_scan.go.
var canonicalSubjectPrefix = map[string]AlertClass{
	"POLECAT_DIED":    ClassPolecatDied,
	"ZOMBIE_DETECTED": ClassZombieDetected,
}

// subjectPrefixRe extracts the leading token from an alert subject line.
var subjectPrefixRe = regexp.MustCompile(`^([A-Z_]+):`)

// RootCauseKey is a stable identifier for a class of repeated alert.
// Format: "<class>:<scope>" where scope is typically the rig name.
type RootCauseKey struct {
	Class AlertClass
	Scope string
}

// String returns the canonical key string used as a label and search term.
func (k RootCauseKey) String() string {
	return fmt.Sprintf("%s:%s", k.Class, k.Scope)
}

// Label returns the beads label used to tag a canonical tracking bead.
func (k RootCauseKey) Label() string {
	return "alert:root-cause:" + k.String()
}

// TypeLabel returns the beads label identifying this as an alert tracking bead.
func (k RootCauseKey) TypeLabel() string {
	return "gt:alert"
}

// AllLabels returns the complete label set for a canonical alert tracking bead.
func (k RootCauseKey) AllLabels(extra ...string) []string {
	labels := []string{k.TypeLabel(), k.Label()}
	labels = append(labels, extra...)
	return labels
}

// ParseSubject extracts an alert class from a message subject.
// Returns the zero class and false if the subject does not match a known
// canonical alert prefix.
func ParseSubject(subject string) (AlertClass, bool) {
	matches := subjectPrefixRe.FindStringSubmatch(subject)
	if len(matches) < 2 {
		return "", false
	}
	cls, ok := canonicalSubjectPrefix[matches[1]]
	return cls, ok
}

// KeyFromSubject builds a RootCauseKey from a subject and scope.
// The second return value is false if the subject is not a canonical alert.
func KeyFromSubject(subject, scope string) (RootCauseKey, bool) {
	cls, ok := ParseSubject(subject)
	if !ok {
		return RootCauseKey{}, false
	}
	return RootCauseKey{Class: cls, Scope: scope}, true
}

// NormalizeClass normalizes a raw alert class string to the canonical form.
func NormalizeClass(raw string) (AlertClass, bool) {
	raw = strings.ToUpper(strings.TrimSpace(raw))
	// Accept either the label form or the subject-prefix form.
	switch raw {
	case "POLECAT_DIED", "POLECAT-DIED", string(ClassPolecatDied):
		return ClassPolecatDied, true
	case "ZOMBIE_DETECTED", "ZOMBIE-DETECTED", string(ClassZombieDetected):
		return ClassZombieDetected, true
	}
	return "", false
}

// KnownClasses returns the set of canonical alert classes.
func KnownClasses() []AlertClass {
	return []AlertClass{ClassPolecatDied, ClassZombieDetected}
}
